### ISSUE TITLE
sealed class generation breaks when referenced from another schema

### ISSUE THREAD

**Issue by Gama11** [cjbooms/fabrikt#103]
It looks like polymorphic class generation breaks as soon as that class is referenced from another schema. Here's an example that adds a `Wrapper` schema to the yml from the readme:

```diff
openapi: 3.0.0
components:
  schemas:
+    Wrapper:
+      type: object
+      properties:
+        polymorph:
+          $ref: '#/components/schemas/PolymorphicEnumDiscriminator'
    PolymorphicEnumDiscriminator:
      type: object
      discriminator:
        propertyName: some_enum
        mapping:
          obj_one: '#/components/schemas/ConcreteImplOne'
          obj_two: '#/components/schemas/ConcreteImplTwo'
      properties:
        some_enum:
          $ref: '#/components/schemas/EnumDiscriminator'
    ConcreteImplOne:
      allOf:
        - $ref: '#/components/schemas/PolymorphicEnumDiscriminator'
        - type: object
          properties:
            some_prop:
              type: string
    ConcreteImplTwo:
      allOf:
        - $ref: '#/components/schemas/PolymorphicEnumDiscriminator'
        - type: object
          properties:
            some_prop:
              type: string
    EnumDiscriminator:
      type: string
      enum:
        - obj_one
        - obj_two
```

In the generated code, `PolymorphicEnumDiscriminator` is generated as a regular `class` and the subtypes are missing:

```kotlin
data class Wrapper(
  @param:JsonProperty("polymorph")
  @get:JsonProperty("polymorph")
  @get:Valid
  val polymorph: PolymorphicEnumDiscriminator? = null
)

class PolymorphicEnumDiscriminator() {
  @param:JsonProperty("some_enum")
  @get:JsonProperty("some_enum")
  @get:NotNull
  val someEnum: EnumDiscriminator
}

enum class EnumDiscriminator(
  @JsonValue
  val value: String
) {
  OBJ_ONE("obj_one"),

  OBJ_TWO("obj_two");

  companion object {
    private val mapping: Map<String, EnumDiscriminator> =
        values().associateBy(EnumDiscriminator::value)

    fun fromValue(value: String): EnumDiscriminator? = mapping[value]
  }
}
```

**Comment by cjbooms** [comment]
Thanks for the report. This is fixed in 2.2.0 which I have just promoted to maven central

**Comment by Gama11** [comment]
That was quick! Thanks. :)

**Comment by Gama11** [comment]
It seems this is not completely fixed, I can still trigger the problem if the `$ref` is in an Array's `items` instead:

```yaml
    Wrapper:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PolymorphicEnumDiscriminator'
```

```kotlin
class PolymorphicEnumDiscriminator() {
  @param:JsonProperty("some_enum")
  @get:JsonProperty("some_enum")
  @get:NotNull
  val someEnum: EnumDiscriminator // Compiler error: "Property must be initialized or be abstract"
}
```

**Comment by cjbooms** [comment]
Forgot about arrays. Fixed now. The inline generation logic is actually a lot saner now :)
