### ISSUE TITLE
Unable to use sealed classes with oneOf in application using ktor: "Class discriminator was missing"

### ISSUE THREAD

**Issue by Palleas** [cjbooms/fabrikt#341]
Hi there! We have a Ktor project where we using an openapi specification and fabrikt. I've introduced a new operation that accepts a object which uses `oneOf` (since it looks like fabrikt is the first tool that actually seem to support it? 🎉 ), but it looks like the generated code is missing something to allow deserialization to work properly. I thought it was an issue with our code but I've been able to reproduce the issue using the example spec.

TL;DR: I've created a repo to test the issue [here](https://github.com/Palleas/ktor-discriminator-sample)

I've updated the specification [provided here](https://github.com/cjbooms/fabrikt/blob/master/src/test/resources/examples/discriminatedOneOf/api.yaml) to include a GET and a POST operation. The get returns a `SomeObj` and the post accepts a `SomeObj` and returns one as well: 

```yaml
paths:
    /some:
        post:
            operationId: sendSomeObject
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/State"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SomeObj"
        get:
            operationId: getSomeObject
            responses:
                200:
                    description: Success response
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SomeObj"
```

And I've registered it here: 
```kotlin
fun Application.configureRouting() {
    routing {
        someRoutes(object: SomeController {
            override suspend fun getSomeObject(call: TypedApplicationCall<SomeObj>) {
                call.respondTyped(SomeObj(state = StateA()))
            }

            override suspend fun sendSomeObject(state: State, call: TypedApplicationCall<SomeObj>) {
                call.respondTyped(SomeObj(state = state))
            }
        })
    }
}
```

Finally, Ktor's content negociation plugin (with json) is configured like this: 
```kotlin
    install(ContentNegotiation) {
        json()
    }
```

After starting the application, sending a GET request to `/some` works as expected, with both StateA and StateB, but the deserialization fails in the POST request and returns a 400. Here is what you can read in the logs:

```
io.ktor.server.plugins.BadRequestException: Failed to convert request body to class com.example.generated.models.State
...giant stack from ktor...
Caused by: io.ktor.serialization.JsonConvertException: Illegal input: Class discriminator was missing and no default serializers were registered in the polymorphic scope of 'State'.
JSON input: {"state":{"type":"a","status":"a"}}
	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:77)
	at io.ktor.server.plugins.contentnegotiation.RequestConverterKt.convertBody(RequestConverter.kt:67)
	... 100 common frames omitted
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Class discriminator was missing and no default serializers were registered in the polymorphic scope of 'State'.
JSON input: {"state":{"type":"a","status":"a"}}
```

I started brushing up on kotlinx.serialization and the section on polymorphism covers a lot of use cases, but it's not clear to me if the generator needs to be tweaked to include a `JsonClassDiscriminator` or something? Happy to provide more details and help with a fix if I can, but I'm just curious if I'm missing something first!

Thanks!

**Comment by Palleas** [comment]
Going to close this for now because I don't think it's an issue with the generated code.

**Comment by cjbooms** [comment]
Thanks @Palleas. We'd have to wait for an answer from the contributors who added the ktor and kotlinx.serialization anyway, I am not familiar with either.

**Comment by Palleas** [comment]
I've dug a little bit further and I realized that I needed 2 things to make my use case work: 
- Add a `JSONClassDiscriminator` annotation (which also requires an OptIn into the Serialization whatever from Kotlin) 
- Add a `Serializable` on my enum class. 
I'll re-open with a clearer example once I'm fluent in kotlinx.serialization !

**Comment by ulrikandersen** [comment]
Hi @Palleas,

I've recently become aware of this limitation in the generation of the polymorphic models myself and have been working on a fix [over here](https://github.com/ulrikandersen/fabrikt/pull/5). 

It is still not yet completely done (there are some things to be discussed), but you are on to the right cause: `JSONClassDiscriminator` is needed when the discriminator name is not `type`.

So for now Kotlin serialization with polymorphic models is broken, unless the discriminator property is left out entirely from the child schemas (this is probably not even valid OpenAPI 3), which is the case in [the end2end test of Phone](https://github.com/cjbooms/fabrikt/blob/master/end2end-tests/models-kotlinx/openapi/api.yaml#L62).

**Comment by Palleas** [comment]
Oh, that's good news, I'll keep an eye on it then, thanks! Not sure if that's already handled your PR, but I noticed that the generated discriminator itself was missing the `@Serializable` annotation as well.

**Comment by ulrikandersen** [comment]
@Palleas With the release of v19.1.0, this issue should be resolved. Please take it for a spin and let us know how it goes!

**Comment by Palleas** [comment]
> @Palleas With the release of [v19.1.0](https://github.com/cjbooms/fabrikt/releases/tag/19.1.0), this issue should be resolved. Please take it for a spin and let us know how it goes!

I've updated to 19.1.0 but it's still missing a few things:
- It looks like the discriminator is no longer generated in the subclass 
- I still need to add the `Serializable` annotation to the generated discriminator enum 

Let me know if you want me to provide a reproducible case!

**Comment by ulrikandersen** [comment]
> Let me know if you want me to provide a reproducible case!

That would definitely be useful 👍 Just the OpenAPI spec.
